rickshaw:
  css: [css/rickshaw.min.css]
  jshead: [js/d3.v2.min.js, js/rickshaw.min.js]
  cdn:
    css: 
      - "http://cdn.strategiqcommerce.com/ajax/libs/rickshaw/1.2.1/rickshaw.min.css"
    jshead:
      - "http://d3js.org/d3.v2.min.js"
      - "http://cdn.strategiqcommerce.com/ajax/libs/rickshaw/1.2.1/rickshaw.min.js"
